/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ASpace: typeof import('ant-design-vue/es')['Space']
    CreateArticle: typeof import('./src/components/dashboard/Article/CreateArticle.vue')['default']
    DashboardHome: typeof import('./src/components/dashboard/Home/DashboardHome.vue')['default']
    DashboardSetting: typeof import('./src/components/dashboard/Setting/DashboardSetting.vue')['default']
    Footer: typeof import('./src/components/Moment/Footer.vue')['default']
    Header: typeof import('./src/components/dashboard/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
